# Retrain Triple-Barrier Transformer

Load a trained triple-barrier Transformer checkpoint, fine-tune it on 15-minute labelled feature data for one or two selected stocks, save a versioned checkpoint, and run one inference example.

In [1]:
from datetime import datetime
from pathlib import Path
import random
import sys

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
PACKAGE_SRC = PROJECT_ROOT / "packages" / "src"
if str(PACKAGE_SRC) not in sys.path:
    sys.path.insert(0, str(PACKAGE_SRC))

PROJECT_ROOT

PosixPath('/Users/akash/PycharmProjects/AlgoTrade')

In [2]:
import pandas as pd
import torch
from torch import nn
from torch.utils.data import DataLoader, random_split

from tradingbot.models import TransformerWindowDataset, build_transformer

DATA_DIR = PROJECT_ROOT / "data" / "historic_candle_feature"
MODEL_DIR = PROJECT_ROOT / "data" / "models"
MODEL_DIR.mkdir(parents=True, exist_ok=True)

BASE_CHECKPOINT_PATH = MODEL_DIR / "triple_barrier_transformer.pt"  # set None to auto-pick the latest versioned base model
BASE_CHECKPOINT_GLOB = "triple_barrier_transformer_classification_*_valacc_*.pt"
CHECKPOINT_PREFIX = "triple_barrier_transformer"

TIMEFRAME = "15minute"
RETRAIN_STOCKS = ["AXISBANK"]  # choose one or two symbols, e.g. ["AXISBANK", "HDFCBANK"]

SEED = 42
VALIDATION_FRACTION = 0.2
BATCH_SIZE = 64
EPOCHS = 20
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-2
MAX_ROWS_PER_FILE = None

LABEL_COLUMNS = [
    "triple_barrier_label_lower",
    "triple_barrier_label_neutral",
    "triple_barrier_label_upper",
]
REGRESSION_COLUMNS = ["triple_barrier_return"]

random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    DEVICE = torch.device("cuda")
elif torch.backends.mps.is_available():
    DEVICE = torch.device("mps")
else:
    DEVICE = torch.device("cpu")

DEVICE

device(type='mps')

In [3]:
def resolve_base_checkpoint():
    if BASE_CHECKPOINT_PATH is not None and Path(BASE_CHECKPOINT_PATH).exists():
        return Path(BASE_CHECKPOINT_PATH)
    candidates = sorted(
        MODEL_DIR.glob(BASE_CHECKPOINT_GLOB),
        key=lambda path: path.stat().st_mtime,
    )
    if not candidates:
        raise FileNotFoundError(
            f"No base checkpoint found. Checked {BASE_CHECKPOINT_PATH} and {MODEL_DIR / BASE_CHECKPOINT_GLOB}"
        )
    return candidates[-1]


base_checkpoint_path = resolve_base_checkpoint()
base_checkpoint = torch.load(base_checkpoint_path, map_location=DEVICE)
base_model_config = base_checkpoint["model_config"]
feature_columns = base_model_config.get("feature_columns") or base_checkpoint.get("feature_columns")
if not feature_columns:
    raise ValueError("Base checkpoint does not include feature_columns; retraining cannot align the dataset.")

OUTPUT_TYPE = base_model_config["output_type"]
CONTEXT_LENGTH = base_checkpoint.get("context_length", 64)
TARGET_OFFSET = base_checkpoint.get("target_offset", 0)

if OUTPUT_TYPE == "classification":
    target_mode = "class_index"
    target_kwargs = {"label_columns": base_checkpoint.get("label_columns") or LABEL_COLUMNS}
    output_dim = len(target_kwargs["label_columns"])
else:
    target_mode = "regression"
    target_kwargs = {"target_columns": base_checkpoint.get("target_columns") or REGRESSION_COLUMNS}
    output_dim = len(target_kwargs["target_columns"])

{
    "base_checkpoint": base_checkpoint_path.name,
    "objective_type": OUTPUT_TYPE,
    "context_length": CONTEXT_LENGTH,
    "target_offset": TARGET_OFFSET,
    "feature_count": len(feature_columns),
}

{'base_checkpoint': 'triple_barrier_transformer.pt',
 'objective_type': 'classification',
 'context_length': 128,
 'target_offset': 0,
 'feature_count': 21}

In [4]:
if not 1 <= len(RETRAIN_STOCKS) <= 2:
    raise ValueError("Choose one or two stocks in RETRAIN_STOCKS.")

matched_files = []
missing_stocks = []
for stock in RETRAIN_STOCKS:
    matches = sorted(DATA_DIR.glob(f"{stock}_{TIMEFRAME}_*_features_triple_barrier.csv"))
    if matches:
        matched_files.extend(matches)
    else:
        missing_stocks.append(stock)

if missing_stocks:
    raise FileNotFoundError(f"No {TIMEFRAME} labelled feature files found for: {missing_stocks}")

schema = pd.read_csv(matched_files[0], nrows=0).columns.tolist()
missing_features = [column for column in feature_columns if column not in schema]
required_targets = target_kwargs.get("label_columns") or target_kwargs.get("target_columns") or []
missing_targets = [column for column in required_targets if column not in schema]
if missing_features or missing_targets:
    raise ValueError(
        f"Retrain files do not match the base checkpoint schema. Missing features={missing_features}, missing targets={missing_targets}"
    )

pd.DataFrame({"matched_file": [path.name for path in matched_files]})

                                        matched_file
0  AXISBANK_15minute_1990-01-01T00-00-00plus05-30...

In [5]:
full_dataset = TransformerWindowDataset(
    matched_files,
    feature_columns=feature_columns,
    context_length=CONTEXT_LENGTH,
    target_mode=target_mode,
    target_offset=TARGET_OFFSET,
    max_rows_per_file=MAX_ROWS_PER_FILE,
    **target_kwargs,
)
if len(full_dataset) == 0:
    raise ValueError(f"Retraining dataset is empty. Skipped files: {full_dataset.skipped[:5]}")

val_size = max(1, int(len(full_dataset) * VALIDATION_FRACTION))
train_size = len(full_dataset) - val_size
if train_size <= 0:
    raise ValueError("Not enough retraining windows for a train/validation split.")

generator = torch.Generator().manual_seed(SEED)
train_dataset, val_dataset = random_split(
    full_dataset,
    [train_size, val_size],
    generator=generator,
)

pin_memory = DEVICE.type == "cuda"
train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=0,
    pin_memory=pin_memory,
)
val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0,
    pin_memory=pin_memory,
)

{
    "total_windows": len(full_dataset),
    "train_windows": len(train_dataset),
    "val_windows": len(val_dataset),
    "label_counts": None if full_dataset.label_counts is None else full_dataset.label_counts.tolist(),
    "skipped": full_dataset.skipped[:5],
}

{'total_windows': 69312,
 'train_windows': 55450,
 'val_windows': 13862,
 'label_counts': [36521, 280, 32511],
 'skipped': []}

In [6]:
builder_config = {
    key: value
    for key, value in base_model_config.items()
    if key not in {"feature_columns", "file_glob", "timeframe_file_pattern", "matched_files"}
}
model = build_transformer(**builder_config).to(DEVICE)
model.load_state_dict(base_checkpoint["model_state_dict"])

if OUTPUT_TYPE == "classification":
    class_weight = None
    if full_dataset.label_counts is not None and (full_dataset.label_counts > 0).all():
        counts = torch.tensor(full_dataset.label_counts, dtype=torch.float32, device=DEVICE)
        class_weight = counts.sum() / (counts.numel() * counts)
    criterion = nn.CrossEntropyLoss(weight=class_weight)
else:
    criterion = nn.MSELoss()

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
)

sum(parameter.numel() for parameter in model.parameters())

30819

In [7]:
def move_batch(batch, device):
    x, y = batch
    return x.to(device), y.to(device)


def classification_metrics(correct, total, true_positive, false_positive, false_negative):
    precision = true_positive / (true_positive + false_positive).clamp_min(1)
    recall = true_positive / (true_positive + false_negative).clamp_min(1)
    f1 = 2 * precision * recall / (precision + recall).clamp_min(1e-12)
    return {
        "accuracy": correct / max(total, 1),
        "precision_macro": precision.mean().item(),
        "recall_macro": recall.mean().item(),
        "f1_macro": f1.mean().item(),
        "precision_by_class": precision.cpu().tolist(),
        "recall_by_class": recall.cpu().tolist(),
        "f1_by_class": f1.cpu().tolist(),
    }


def checkpoint_path_for(objective_type, final_val_accuracy):
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    accuracy_text = "na" if final_val_accuracy is None else f"{final_val_accuracy:.4f}"
    stock_text = "-".join(RETRAIN_STOCKS)
    return MODEL_DIR / f"{CHECKPOINT_PREFIX}_{objective_type}_{stock_text}_{TIMEFRAME}_{timestamp}_valacc_{accuracy_text}.pt"


def train_one_epoch(model, loader):
    model.train()
    total_loss = 0.0
    total_items = 0

    for batch in loader:
        x, y = move_batch(batch, DEVICE)
        optimizer.zero_grad(set_to_none=True)
        prediction = model(x)
        loss = criterion(prediction, y)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()

        batch_size = x.size(0)
        total_loss += loss.item() * batch_size
        total_items += batch_size

    return total_loss / max(total_items, 1)


@torch.no_grad()
def evaluate(model, loader):
    model.eval()
    total_loss = 0.0
    total_items = 0

    if OUTPUT_TYPE == "classification":
        class_count = output_dim
        correct = 0
        true_positive = torch.zeros(class_count, dtype=torch.float32, device=DEVICE)
        false_positive = torch.zeros(class_count, dtype=torch.float32, device=DEVICE)
        false_negative = torch.zeros(class_count, dtype=torch.float32, device=DEVICE)

    for batch in loader:
        x, y = move_batch(batch, DEVICE)
        prediction = model(x)
        loss = criterion(prediction, y)

        batch_size = x.size(0)
        total_loss += loss.item() * batch_size
        total_items += batch_size

        if OUTPUT_TYPE == "classification":
            predicted = prediction.argmax(dim=-1)
            correct += (predicted == y).sum().item()
            for class_index in range(class_count):
                predicted_class = predicted == class_index
                actual_class = y == class_index
                true_positive[class_index] += (predicted_class & actual_class).sum()
                false_positive[class_index] += (predicted_class & ~actual_class).sum()
                false_negative[class_index] += (~predicted_class & actual_class).sum()

    metrics = {"loss": total_loss / max(total_items, 1)}
    if OUTPUT_TYPE == "classification":
        metrics.update(
            classification_metrics(correct, total_items, true_positive, false_positive, false_negative)
        )
    return metrics


def prefixed_metrics(prefix, metrics):
    return {f"{prefix}_{key}": value for key, value in metrics.items()}


history = []

for epoch in range(1, EPOCHS + 1):
    train_loss = train_one_epoch(model, train_loader)
    train_metrics = evaluate(model, train_loader)
    val_metrics = evaluate(model, val_loader)
    row = {
        "epoch": epoch,
        "train_optimized_loss": train_loss,
        **prefixed_metrics("train", train_metrics),
        **prefixed_metrics("val", val_metrics),
    }
    history.append(row)
    print(row)

final_metrics = history[-1]
final_val_accuracy = final_metrics.get("val_accuracy")
saved_checkpoint_path = checkpoint_path_for(OUTPUT_TYPE, final_val_accuracy)
model_config = {
    **base_model_config,
    "feature_columns": feature_columns,
    "retrain_stocks": RETRAIN_STOCKS,
    "timeframe": TIMEFRAME,
    "matched_files": [path.name for path in matched_files],
    "base_checkpoint": base_checkpoint_path.name,
}
checkpoint_context = {
    "model_state_dict": model.state_dict(),
    "model_config": model_config,
    "feature_columns": feature_columns,
    "label_columns": target_kwargs.get("label_columns"),
    "target_columns": target_kwargs.get("target_columns"),
    "context_length": CONTEXT_LENGTH,
    "target_offset": TARGET_OFFSET,
    "history": history,
    "final_metrics": final_metrics,
    "objective_type": OUTPUT_TYPE,
    "base_checkpoint": base_checkpoint_path.name,
    "retrain_stocks": RETRAIN_STOCKS,
    "timeframe": TIMEFRAME,
    "matched_files": [path.name for path in matched_files],
    "saved_checkpoint_name": saved_checkpoint_path.name,
}
torch.save(checkpoint_context, saved_checkpoint_path)
print(f"Saved retrained model to {saved_checkpoint_path}")

pd.DataFrame(history)

{'epoch': 1, 'train_optimized_loss': 1.434531275366103, 'train_loss': 1.3491666340698951, 'train_accuracy': 0.5232281334535618, 'train_precision_macro': 0.34234490990638733, 'train_recall_macro': 0.34215298295021057, 'train_f1_macro': 0.3312370181083679, 'train_precision_by_class': [0.5373283624649048, 0.0, 0.489706426858902], 'train_recall_by_class': [0.7165846824645996, 0.0, 0.30987435579299927], 'train_f1_by_class': [0.6141434907913208, 0.0, 0.37956756353378296], 'val_loss': 1.1886535963271194, 'val_accuracy': 0.5254653008223922, 'val_precision_macro': 0.34578457474708557, 'val_recall_macro': 0.34466519951820374, 'val_f1_macro': 0.33338236808776855, 'val_precision_by_class': [0.5352790355682373, 0.0, 0.5020747184753418], 'val_recall_by_class': [0.72066730260849, 0.0, 0.31332826614379883], 'val_f1_by_class': [0.614290714263916, 0.0, 0.3858563303947449]}
{'epoch': 2, 'train_optimized_loss': 1.2968342342153125, 'train_loss': 1.2785942198952862, 'train_accuracy': 0.5405049594229036, 'train_precision_macro': 0.3564138412475586, 'train_recall_macro': 0.35195693373680115, 'train_f1_macro': 0.33541715145111084, 'train_precision_by_class': [0.5464441180229187, 0.0, 0.5227974653244019], 'train_recall_by_class': [0.7752494215965271, 0.0, 0.2806212902069092], 'train_f1_by_class': [0.6410419344902039, 0.0, 0.36520954966545105], 'val_loss': 1.1612279568807573, 'val_accuracy': 0.5375126244409176, 'val_precision_macro': 0.356130450963974, 'val_recall_macro': 0.35105904936790466, 'val_f1_macro': 0.3328216075897217, 'val_precision_by_class': [0.5406954288482666, 0.0, 0.5276959538459778], 'val_recall_by_class': [0.7803667187690735, 0.0, 0.2728103697299957], 'val_f1_by_class': [0.6387901306152344, 0.0, 0.3596746623516083]}
{'epoch': 3, 'train_optimized_loss': 1.2897869982452839, 'train_loss': 1.2406322939101375, 'train_accuracy': 0.5514337240757439, 'train_precision_macro': 0.36492955684661865, 'train_recall_macro': 0.36117568612098694, 'train_f1_macro': 0.3514470160007477, 'train_precision_by_class': [0.5573757886886597, 0.0, 0.5374128818511963], 'train_recall_by_class': [0.7416632771492004, 0.0, 0.34186387062072754], 'train_f1_by_class': [0.636447548866272, 0.0, 0.41789355874061584], 'val_loss': 1.1238739842495487, 'val_accuracy': 0.5393882556629634, 'val_precision_macro': 0.35704588890075684, 'val_recall_macro': 0.3539252281188965, 'val_f1_macro': 0.3428455889225006, 'val_precision_by_class': [0.5447959303855896, 0.0, 0.5263416767120361], 'val_recall_by_class': [0.73610919713974, 0.0, 0.3256664276123047], 'val_f1_by_class': [0.626165509223938, 0.0, 0.4023713171482086]}
{'epoch': 4, 'train_optimized_loss': 1.2919453060250758, 'train_loss': 1.2010080645469206, 'train_accuracy': 0.5475743913435528, 'train_precision_macro': 0.3651143014431, 'train_recall_macro': 0.3667789399623871, 'train_f1_macro': 0.3655843734741211, 'train_precision_by_class': [0.5778396725654602, 0.0, 0.5175031423568726], 'train_recall_by_class': [0.5459546446800232, 0.0, 0.5543822050094604], 'train_f1_by_class': [0.5614448189735413, 0.0, 0.5353082418441772], 'val_loss': 1.1066557435207838, 'val_accuracy': 0.5398932332996682, 'val_precision_macro': 0.3598703444004059, 'val_recall_macro': 0.36109569668769836, 'val_f1_macro': 0.3602895736694336, 'val_precision_by_class': [0.5641173124313354, 0.0, 0.5154937505722046], 'val_recall_by_class': [0.5410175323486328, 0.0, 0.5422695875167847], 'val_f1_by_class': [0.5523260235786438, 0.0, 0.5285427570343018]}
{'epoch': 5, 'train_optimized_loss': 1.2650185397533387, 'train_loss': 1.2289584559100075, 'train_accuracy': 0.5853381424706943, 'train_precision_macro': 0.3916541635990143, 'train_recall_macro': 0.3841385543346405, 'train_f1_macro': 0.376027911901474, 'train_precision_by_class': [0.5820648670196533, 0.0, 0.5928976535797119], 'train_recall_by_class': [0.7695435285568237, 0.0, 0.3828721046447754], 'train_f1_by_class': [0.6628018021583557, 0.0, 0.4652818441390991], 'val_loss': 1.1436429284744114, 'val_accuracy': 0.5720675227239936, 'val_precision_macro': 0.3832227885723114, 'val_recall_macro': 0.37592896819114685, 'val_f1_macro': 0.36632290482521057, 'val_precision_by_class': [0.5680630803108215, 0.0, 0.5816052556037903], 'val_recall_by_class': [0.7646490931510925, 0.0, 0.3631378412246704], 'val_f1_by_class': [0.6518570184707642, 0.0, 0.44711175560951233]}
{'epoch': 6, 'train_optimized_loss': 1.2566358677625011, 'train_loss': 1.201286705929057, 'train_accuracy': 0.5974752028854824, 'train_precision_macro': 0.39920350909233093, 'train_recall_macro': 0.3934919536113739, 'train_f1_macro': 0.38828718662261963, 'train_precision_by_class': [0.5948499441146851, 0.0, 0.6027605533599854], 'train_recall_by_class': [0.7529725432395935, 0.0, 0.4275032877922058], 'train_f1_by_class': [0.6646360754966736, 0.0, 0.5002254843711853], 'val_loss': 1.1484473457568274, 'val_accuracy': 0.577261578415813, 'val_precision_macro': 0.3853938579559326, 'val_recall_macro': 0.3805335462093353, 'val_f1_macro': 0.37437188625335693, 'val_precision_by_class': [0.5756564736366272, 0.0, 0.5805251598358154], 'val_recall_by_class': [0.7374879121780396, 0.0, 0.40411272644996643], 'val_f1_by_class': [0.6466001272201538, 0.0, 0.476515531539917]}
{'epoch': 7, 'train_optimized_loss': 1.2300905622997405, 'train_loss': 1.1806519134825044, 'train_accuracy': 0.6117944093778178, 'train_precision_macro': 0.42944416403770447, 'train_recall_macro': 0.39811936020851135, 'train_f1_macro': 0.3790113627910614, 'train_precision_by_class': [0.5887575745582581, 0.0, 0.699574887752533], 'train_recall_by_class': [0.8835588097572327, 0.0, 0.31079936027526855], 'train_f1_by_class': [0.7066441774368286, 0.0, 0.4303898811340332], 'val_loss': 1.1299389704122393, 'val_accuracy': 0.5912566729187707, 'val_precision_macro': 0.4136750400066376, 'val_recall_macro': 0.3855867087841034, 'val_f1_macro': 0.36277762055397034, 'val_precision_by_class': [0.5718277096748352, 0.0, 0.6691973805427551], 'val_recall_by_class': [0.8748103976249695, 0.0, 0.2819497287273407], 'val_f1_by_class': [0.6915907859802246, 0.0, 0.396742045879364]}
{'epoch': 8, 'train_optimized_loss': 1.2101747734273631, 'train_loss': 1.2096937776428822, 'train_accuracy': 0.6204869251577998, 'train_precision_macro': 0.5252322554588318, 'train_recall_macro': 0.41177740693092346, 'train_f1_macro': 0.41049373149871826, 'train_precision_by_class': [0.6186213493347168, 0.3333333432674408, 0.6237419843673706], 'train_recall_by_class': [0.7414240837097168, 0.0042372881434857845, 0.48967084288597107], 'train_f1_by_class': [0.6744785904884338, 0.008368200622498989, 0.5486343502998352], 'val_loss': 1.1581030122268219, 'val_accuracy': 0.6012840859904776, 'val_precision_macro': 0.4015423357486725, 'val_recall_macro': 0.3977881669998169, 'val_f1_macro': 0.39453577995300293, 'val_precision_by_class': [0.5988425016403198, 0.0, 0.6057844758033752], 'val_recall_by_class': [0.7275609970092773, 0.0, 0.46580350399017334], 'val_f1_by_class': [0.656956136226654, 0.0, 0.52665114402771]}
{'epoch': 9, 'train_optimized_loss': 1.1897628482641456, 'train_loss': 1.1238067945969652, 'train_accuracy': 0.6349684400360686, 'train_precision_macro': 0.5994840264320374, 'train_recall_macro': 0.4211730659008026, 'train_f1_macro': 0.41764035820961, 'train_precision_by_class': [0.6154295206069946, 0.5, 0.6830226182937622], 'train_recall_by_class': [0.8285841345787048, 0.012711863964796066, 0.4222230911254883], 'train_f1_by_class': [0.706274688243866, 0.024793386459350586, 0.5218530297279358], 'val_loss': 1.129043519643113, 'val_accuracy': 0.6065502813446834, 'val_precision_macro': 0.4121614694595337, 'val_recall_macro': 0.39868196845054626, 'val_f1_macro': 0.3891369104385376, 'val_precision_by_class': [0.5911841988563538, 0.0, 0.6453002095222473], 'val_recall_by_class': [0.8080794215202332, 0.0, 0.38796648383140564], 'val_f1_by_class': [0.6828216910362244, 0.0, 0.4845890402793884]}
{'epoch': 10, 'train_optimized_loss': 1.156922750466573, 'train_loss': 1.0932947131080386, 'train_accuracy': 0.64, 'train_precision_macro': 0.5702977180480957, 'train_recall_macro': 0.42814329266548157, 'train_f1_macro': 0.43020355701446533, 'train_precision_by_class': [0.6364902853965759, 0.4285714328289032, 0.6458313465118408], 'train_recall_by_class': [0.7492483258247375, 0.012711863964796066, 0.5224697589874268], 'train_f1_by_class': [0.6882817149162292, 0.02469135820865631, 0.5776376128196716], 'val_loss': 1.1077328034851428, 'val_accuracy': 0.6110229404126388, 'val_precision_macro': 0.4078512191772461, 'val_recall_macro': 0.404796838760376, 'val_f1_macro': 0.40240415930747986, 'val_precision_by_class': [0.6090338826179504, 0.0, 0.6145198345184326], 'val_recall_by_class': [0.7231490612030029, 0.0, 0.4912414252758026], 'val_f1_by_class': [0.661203920841217, 0.0, 0.5460085868835449]}
{'epoch': 11, 'train_optimized_loss': 1.1434891936540388, 'train_loss': 1.0685000208006774, 'train_accuracy': 0.6535437330928765, 'train_precision_macro': 0.6346232295036316, 'train_recall_macro': 0.43593502044677734, 'train_f1_macro': 0.4360755980014801, 'train_precision_by_class': [0.6326786875724792, 0.5714285969734192, 0.6997623443603516], 'train_recall_by_class': [0.8255432844161987, 0.016949152573943138, 0.46531257033348083], 'train_f1_by_class': [0.7163568735122681, 0.03292180970311165, 0.5589480996131897], 'val_loss': 1.1036654940210127, 'val_accuracy': 0.6214110517962776, 'val_precision_macro': 0.4215637147426605, 'val_recall_macro': 0.40930041670799255, 'val_f1_macro': 0.4021975100040436, 'val_precision_by_class': [0.6045016050338745, 0.0, 0.6601895689964294], 'val_recall_by_class': [0.8035295605659485, 0.0, 0.4243716597557068], 'val_f1_by_class': [0.6899490356445312, 0.0, 0.5166434645652771]}
{'epoch': 12, 'train_optimized_loss': 1.135979573118246, 'train_loss': 1.0827067116039955, 'train_accuracy': 0.657619477006312, 'train_precision_macro': 0.6970306038856506, 'train_recall_macro': 0.437326580286026, 'train_f1_macro': 0.4364335238933563, 'train_precision_by_class': [0.6360272765159607, 0.75, 0.705064594745636], 'train_recall_by_class': [0.8281741142272949, 0.012711863964796066, 0.4710938036441803], 'train_f1_by_class': [0.7194929718971252, 0.02499999850988388, 0.5648075342178345], 'val_loss': 1.124605778585934, 'val_accuracy': 0.6244409176165056, 'val_precision_macro': 0.4233447313308716, 'val_recall_macro': 0.4114473760128021, 'val_f1_macro': 0.40473973751068115, 'val_precision_by_class': [0.6076570153236389, 0.0, 0.6623771786689758], 'val_recall_by_class': [0.803115963935852, 0.0, 0.4312261939048767], 'val_f1_by_class': [0.6918463110923767, 0.0, 0.5223729014396667]}
{'epoch': 13, 'train_optimized_loss': 1.1237981568380344, 'train_loss': 1.0392805436519592, 'train_accuracy': 0.6663841298467087, 'train_precision_macro': 0.6642886400222778, 'train_recall_macro': 0.44925472140312195, 'train_f1_macro': 0.4542335569858551, 'train_precision_by_class': [0.6446624994277954, 0.6363636255264282, 0.7118398547172546], 'train_recall_by_class': [0.8261582851409912, 0.029661016538739204, 0.491944819688797], 'train_f1_by_class': [0.7242122888565063, 0.056680165231227875, 0.5818082690238953], 'val_loss': 1.105021205054718, 'val_accuracy': 0.6305727889193479, 'val_precision_macro': 0.42665648460388184, 'val_recall_macro': 0.41595587134361267, 'val_f1_macro': 0.4103846251964569, 'val_precision_by_class': [0.6140537261962891, 0.0, 0.6659157276153564], 'val_recall_by_class': [0.7976009845733643, 0.0, 0.450266569852829], 'val_f1_by_class': [0.6938946843147278, 0.0, 0.5372591614723206]}
{'epoch': 14, 'train_optimized_loss': 1.1342319996019437, 'train_loss': 1.0202515063810391, 'train_accuracy': 0.6739404869251578, 'train_precision_macro': 0.6348274350166321, 'train_recall_macro': 0.45505473017692566, 'train_f1_macro': 0.4610128700733185, 'train_precision_by_class': [0.6545045971870422, 0.5384615659713745, 0.7115160822868347], 'train_recall_by_class': [0.8163865208625793, 0.029661016538739204, 0.5191166400909424], 'train_f1_by_class': [0.7265374660491943, 0.05622490122914314, 0.6002762913703918], 'val_loss': 1.0957022633254656, 'val_accuracy': 0.638940989756168, 'val_precision_macro': 0.43076589703559875, 'val_recall_macro': 0.42225024104118347, 'val_f1_macro': 0.4183220863342285, 'val_precision_by_class': [0.6242198348045349, 0.0, 0.6680778861045837], 'val_recall_by_class': [0.7860195636749268, 0.0, 0.48073115944862366], 'val_f1_by_class': [0.6958378553390503, 0.0, 0.5591283440589905]}
{'epoch': 15, 'train_optimized_loss': 1.0999341834741632, 'train_loss': 0.9747311695015463, 'train_accuracy': 0.6792605951307484, 'train_precision_macro': 0.6000798344612122, 'train_recall_macro': 0.466312050819397, 'train_f1_macro': 0.47762978076934814, 'train_precision_by_class': [0.6630474328994751, 0.4285714328289032, 0.7086206078529358], 'train_recall_by_class': [0.8053846955299377, 0.050847455859184265, 0.5427041053771973], 'train_f1_by_class': [0.7273175716400146, 0.09090909361839294, 0.6146627068519592], 'val_loss': 1.081983434484903, 'val_accuracy': 0.641249458952532, 'val_precision_macro': 0.43037858605384827, 'val_recall_macro': 0.4245734214782715, 'val_f1_macro': 0.4219846725463867, 'val_precision_by_class': [0.6310051083564758, 0.0, 0.6601307392120361], 'val_recall_by_class': [0.7660278677940369, 0.0, 0.5076923370361328], 'val_f1_by_class': [0.6919915676116943, 0.0, 0.5739625096321106]}
{'epoch': 16, 'train_optimized_loss': 1.0824232268161447, 'train_loss': 1.0007064480906247, 'train_accuracy': 0.6848692515779982, 'train_precision_macro': 0.6560596823692322, 'train_recall_macro': 0.473494291305542, 'train_f1_macro': 0.48773059248924255, 'train_precision_by_class': [0.6623720526695251, 0.5769230723381042, 0.7288839221000671], 'train_recall_by_class': [0.8290966153144836, 0.06355932354927063, 0.5278270244598389], 'train_f1_by_class': [0.7364156246185303, 0.11450381577014923, 0.6122722029685974], 'val_loss': 1.1250720262923053, 'val_accuracy': 0.6464435146443515, 'val_precision_macro': 0.436593621969223, 'val_recall_macro': 0.4271791875362396, 'val_f1_macro': 0.42321744561195374, 'val_precision_by_class': [0.6295246481895447, 0.0, 0.6802561283111572], 'val_recall_by_class': [0.7960844039916992, 0.0, 0.48545315861701965], 'val_f1_by_class': [0.70307457447052, 0.0, 0.5665777921676636]}
{'epoch': 17, 'train_optimized_loss': 1.0809124791439424, 'train_loss': 0.9349141981668361, 'train_accuracy': 0.6901532912533814, 'train_precision_macro': 0.622680127620697, 'train_recall_macro': 0.48525679111480713, 'train_f1_macro': 0.5035026669502258, 'train_precision_by_class': [0.6745043992996216, 0.4761904776096344, 0.7173455953598022], 'train_recall_by_class': [0.8056580424308777, 0.08474576473236084, 0.5653665065765381], 'train_f1_by_class': [0.7342706322669983, 0.14388491213321686, 0.6323525905609131], 'val_loss': 1.0893398572521076, 'val_accuracy': 0.6499783581012841, 'val_precision_macro': 0.43619242310523987, 'val_recall_macro': 0.4305966794490814, 'val_f1_macro': 0.42833709716796875, 'val_precision_by_class': [0.638850748538971, 0.0, 0.669726550579071], 'val_recall_by_class': [0.7694746851921082, 0.0, 0.5223153233528137], 'val_f1_by_class': [0.6981049180030823, 0.0, 0.5869063138961792]}
{'epoch': 18, 'train_optimized_loss': 1.0653972432417735, 'train_loss': 1.0052152664968836, 'train_accuracy': 0.6940306582506763, 'train_precision_macro': 0.7146022915840149, 'train_recall_macro': 0.47834816575050354, 'train_f1_macro': 0.4918539822101593, 'train_precision_by_class': [0.6611598134040833, 0.7142857313156128, 0.7683615684509277], 'train_recall_by_class': [0.8682861924171448, 0.06355932354927063, 0.5031989812850952], 'train_f1_by_class': [0.7506978511810303, 0.11673152446746826, 0.6081326603889465], 'val_loss': 1.1552157808547239, 'val_accuracy': 0.6505554754003752, 'val_precision_macro': 0.444216251373291, 'val_recall_macro': 0.42887887358665466, 'val_f1_macro': 0.422837495803833, 'val_precision_by_class': [0.6263781785964966, 0.0, 0.7062706351280212], 'val_recall_by_class': [0.830277144908905, 0.0, 0.45635947585105896], 'val_f1_by_class': [0.7140570878982544, 0.0, 0.5544554591178894]}
{'epoch': 19, 'train_optimized_loss': 1.0638957623558285, 'train_loss': 0.9338389810105505, 'train_accuracy': 0.701370604147881, 'train_precision_macro': 0.6587477326393127, 'train_recall_macro': 0.49604108929634094, 'train_f1_macro': 0.517241895198822, 'train_precision_by_class': [0.6868392825126648, 0.5641025900840759, 0.7253013253211975], 'train_recall_by_class': [0.8057947158813477, 0.09322033822536469, 0.5891081690788269], 'train_f1_by_class': [0.7415769100189209, 0.1599999964237213, 0.650148868560791], 'val_loss': 1.1329028107459163, 'val_accuracy': 0.6580580002885587, 'val_precision_macro': 0.44099029898643494, 'val_recall_macro': 0.43647122383117676, 'val_f1_macro': 0.4348602294921875, 'val_precision_by_class': [0.6482629776000977, 0.0, 0.6747078895568848], 'val_recall_by_class': [0.7640976309776306, 0.0, 0.5453160405158997], 'val_f1_by_class': [0.7014302015304565, 0.0, 0.6031505465507507]}
{'epoch': 20, 'train_optimized_loss': 1.0380360190238471, 'train_loss': 0.9361090786936479, 'train_accuracy': 0.7054824165915239, 'train_precision_macro': 0.6528492569923401, 'train_recall_macro': 0.499856561422348, 'train_f1_macro': 0.5211356282234192, 'train_precision_by_class': [0.6875987648963928, 0.5348837375640869, 0.7360652685165405], 'train_recall_by_class': [0.8178215026855469, 0.09745762497186661, 0.5842904448509216], 'train_f1_by_class': [0.7470778226852417, 0.16487453877925873, 0.6514546275138855], 'val_loss': 1.1388036320519437, 'val_accuracy': 0.6600057711729909, 'val_precision_macro': 0.4652557075023651, 'val_recall_macro': 0.4451022148132324, 'val_f1_macro': 0.4471491277217865, 'val_precision_by_class': [0.6487019062042236, 0.06666667014360428, 0.6803985238075256], 'val_recall_by_class': [0.7716807126998901, 0.022727273404598236, 0.5408986806869507], 'val_f1_by_class': [0.7048674821853638, 0.033898305147886276, 0.602681577205658]}
Saved retrained model to /Users/akash/PycharmProjects/AlgoTrade/data/models/triple_barrier_transformer_classification_AXISBANK_15minute_20260516_022110_valacc_0.6600.pt

,epoch,train_optimized_loss,train_loss,train_accuracy,train_precision_macro,train_recall_macro,train_f1_macro,train_precision_by_class,train_recall_by_class,train_f1_by_class,val_loss,val_accuracy,val_precision_macro,val_recall_macro,val_f1_macro,val_precision_by_class,val_recall_by_class,val_f1_by_class
0,1,1.434531,1.349167,0.523228,0.342345,0.342153,0.331237,"[0.5373283624649048, 0.0, 0.489706426858902]","[0.7165846824645996, 0.0, 0.30987435579299927]","[0.6141434907913208, 0.0, 0.37956756353378296]",1.188654,0.525465,0.345785,0.344665,0.333382,"[0.5352790355682373, 0.0, 0.5020747184753418]","[0.72066730260849, 0.0, 0.31332826614379883]","[0.614290714263916, 0.0, 0.3858563303947449]"
1,2,1.296834,1.278594,0.540505,0.356414,0.351957,0.335417,"[0.5464441180229187, 0.0, 0.5227974653244019]","[0.7752494215965271, 0.0, 0.2806212902069092]","[0.6410419344902039, 0.0, 0.36520954966545105]",1.161228,0.537513,0.356130,0.351059,0.332822,"[0.5406954288482666, 0.0, 0.5276959538459778]","[0.7803667187690735, 0.0, 0.2728103697299957]","[0.6387901306152344, 0.0, 0.3596746623516083]"
2,3,1.289787,1.240632,0.551434,0.364930,0.361176,0.351447,"[0.5573757886886597, 0.0, 0.5374128818511963]","[0.7416632771492004, 0.0, 0.34186387062072754]","[0.636447548866272, 0.0, 0.41789355874061584]",1.123874,0.539388,0.357046,0.353925,0.342846,"[0.5447959303855896, 0.0, 0.5263416767120361]","[0.73610919713974, 0.0, 0.3256664276123047]","[0.626165509223938, 0.0, 0.4023713171482086]"
3,4,1.291945,1.201008,0.547574,0.365114,0.366779,0.365584,"[0.5778396725654602, 0.0, 0.5175031423568726]","[0.5459546446800232, 0.0, 0.5543822050094604]","[0.5614448189735413, 0.0, 0.5353082418441772]",1.106656,0.539893,0.359870,0.361096,0.360290,"[0.5641173124313354, 0.0, 0.5154937505722046]","[0.5410175323486328, 0.0, 0.5422695875167847]","[0.5523260235786438, 0.0, 0.5285427570343018]"
4,5,1.265019,1.228958,0.585338,0.391654,0.384139,0.376028,"[0.5820648670196533, 0.0, 0.5928976535797119]","[0.7695435285568237, 0.0, 0.3828721046447754]","[0.6628018021583557, 0.0, 0.4652818441390991]",1.143643,0.572068,0.383223,0.375929,0.366323,"[0.5680630803108215, 0.0, 0.5816052556037903]","[0.7646490931510925, 0.0, 0.3631378412246704]","[0.6518570184707642, 0.0, 0.44711175560951233]"
5,6,1.256636,1.201287,0.597475,0.399204,0.393492,0.388287,"[0.5948499441146851, 0.0, 0.6027605533599854]","[0.7529725432395935, 0.0, 0.4275032877922058]","[0.6646360754966736, 0.0, 0.5002254843711853]",1.148447,0.577262,0.385394,0.380534,0.374372,"[0.5756564736366272, 0.0, 0.5805251598358154]","[0.7374879121780396, 0.0, 0.40411272644996643]","[0.6466001272201538, 0.0, 0.476515531539917]"
6,7,1.230091,1.180652,0.611794,0.429444,0.398119,0.379011,"[0.5887575745582581, 0.0, 0.699574887752533]","[0.8835588097572327, 0.0, 0.31079936027526855]","[0.7066441774368286, 0.0, 0.4303898811340332]",1.129939,0.591257,0.413675,0.385587,0.362778,"[0.5718277096748352, 0.0, 0.6691973805427551]","[0.8748103976249695, 0.0, 0.2819497287273407]","[0.6915907859802246, 0.0, 0.396742045879364]"
7,8,1.210175,1.209694,0.620487,0.525232,0.411777,0.410494,"[0.6186213493347168, 0.3333333432674408, 0.623...","[0.7414240837097168, 0.0042372881434857845, 0....","[0.6744785904884338, 0.008368200622498989, 0.5...",1.158103,0.601284,0.401542,0.397788,0.394536,"[0.5988425016403198, 0.0, 0.6057844758033752]","[0.7275609970092773, 0.0, 0.46580350399017334]","[0.656956136226654, 0.0, 0.52665114402771]"
8,9,1.189763,1.123807,0.634968,0.599484,0.421173,0.417640,"[0.6154295206069946, 0.5, 0.6830226182937622]","[0.8285841345787048, 0.012711863964796066, 0.4...","[0.706274688243866, 0.024793386459350586, 0.52...",1.129044,0.606550,0.412161,0.398682,0.389137,"[0.5911841988563538, 0.0, 0.6453002095222473]","[0.8080794215202332, 0.0, 0.38796648383140564]","[0.6828216910362244, 0.0, 0.4845890402793884]"
9,10,1.156923,1.093295,0.640000,0.570298,0.428143,0.430204,"[0.6364902853965759, 0.4285714328289032, 0.645...","[0.7492483258247375, 0.012711863964796066, 0.5...","[0.6882817149162292, 0.02469135820865631, 0.57...",1.107733,0.611023,0.407851,0.404797,0.402404,"[0.6090338826179504, 0.0, 0.6145198345184326]","[0.7231490612030029, 0.0, 0.4912414252758026]","[0.661203920841217, 0.0, 0.5460085868835449]"
10,11,1.143489,1.068500,0.653544,0.634623,0.435935,0.436076,"[0.6326786875724792, 0.5714285969734192, 0.699...","[0.8255432844161987, 0.016949152573943138, 0.4...","[0.7163568735122681, 0.03292180970311165, 0.55...",1.103665,0.621411,0.421564,0.409300,0.402198,"[0.6045016050338745, 0.0, 0.6601895689964294]","[0.8035295605659485, 0.0, 0.4243716597557068]","[0.6899490356445312, 0.0, 0.5166434645652771]"
11,12,1.135980,1.082707,0.657619,0.697031,0.437327,0.436434,"[0.6360272765159607, 0.75, 0.705064594745636]","[0.8281741142272949, 0.012711863964796066, 0.4...","[0.7194929718971252, 0.02499999850988388, 0.56...",1.124606,0.624441,0.423345,0.411447,0.404740,"[0.6076570153236389, 0.0, 0.6623771786689758]","[0.803115963935852, 0.0, 0.4312261939048767]","[0.6918463110923767, 0.0, 0.5223729014396667]"
12,13,1.123798,1.039281,0.666384,0.664289,0.449255,0.454234,"[0.6446624994277954, 0.6363636255264282, 0.711...","[0.8261582851409912, 0.029661016538739204, 0.4...","[0.7242122888565063, 0.056680165231227875, 0.5...",1.105021,0.630573,0.426656,0.415956,0.410385,"[0.6140537261962891, 0.0, 0.6659157276153564]","[0.7976009845733643, 0.0, 0.450266569852829]","[0.6938946843147278, 0.0, 0.5372591614723206]"
13,14,1.134232,1.020252,0.673940,0.634827,0.455055,0.461013,"[0.6545045971870422, 0.5384615659713745, 0.711...","[0.8163865208625793, 0.029661016538739204, 0.5...","[0.7265374660491943, 0.05622490122914314, 0.60...",1.095702,0.638941,0.430766,0.422250,0.418322,"[0.6242198348045349, 0.0, 0.6680778861045837]","[0.7860195636749268, 0.0, 0.48073115944862366]","[0.6958378553390503, 0.0, 0.5591283440589905]"
14,15,1.099934,0.974731,0.679261,0.600080,0.466312,0.477630,"[0.6630474328994751, 0.4285714328289032, 0.708...","[0.8053846955299377, 0.050847455859184265, 0.5...","[0.7273175716400146, 0.09090909361839294, 0.61...",1.081983,0.641249,0.430379,0.424573,0.421985,"[0.6310051083564758, 0.0, 0.6601307392120361]","[0.7660278677940369, 0.0, 0.5076923370361328]","[0.6919915676116943, 0.0, 0.5739625096321106]"
15,16,1.082423,1.000706,0.684869,0.656060,0.473494,0.487731,"[0.6623720526695251, 0.5769230723381042, 0.728...","[0.8290966153144836, 0.06355932354927063, 0.52...","[0.7364156246185303, 0.11450381577014923, 0.61...",1.125072,0.646444,0.436594,0.427179,0.423217,"[0.6295246481895447, 0.0, 0.6802561283111572]","[0.7960844039916992, 0.0, 0.48545315861701965]","[0.70307457447052, 0.0, 0.5665777921676636]"
16,17,1.080912,0.934914,0.690153,0.622680,0.485257,0.503503,"[0.6745043992996216, 0.4761904776096344, 0.717...","[0.8056580424308777, 0.08474576473236084, 0.56...","[0.7342706322669983, 0.14388491213321686, 0.63...",1.089340,0.649978,0.436192,0.430597,0.428337,"[0.638850748538971, 0.0, 0.669726550579071]","[0.7694746851921082, 0.0, 0.5223153233528137]","[0.6981049180030823, 0.0, 0.5869063138961792]"
17,18,1.065397,1.005215,0.694031,0.714602,0.478348,0.491854,"[0.6611598134040833, 0.7142857313156128, 0.768...","[0.8682861924171448, 0.06355932354927063, 0.50...","[0.7506978511810303, 0.11673152446746826, 0.60...",1.155216,0.650555,0.444216,0.428879,0.422837,"[0.6263781785964966, 0.0, 0.7062706351280212]","[0.830277144908905, 0.0, 0.45635947585105896]","[0.7140570878982544, 0.0, 0.5544554591178894]"
18,19,1.063896,0.933839,0.701371,0.658748,0.496041,0.517242,"[0.6868392825126648, 0.5641025900840759, 0.725...","[0.8057947158813477, 0.09322033822536469, 0.58...","[0.7415769100189209, 0.1599999964237213, 0.650...",1.132903,0.658058,0.440990,0.436471,0.434860,"[0.6482629776000977, 0.0, 0.6747078895568848]","[0.7640976309776306, 0.0, 0.5453160405158997]","[0.7014302015304565, 0.0, 0.6031505465507507]"
19,20,1.038036,0.936109,0.705482,0.652849,0.499857,0.521136,"[0.6875987648963928, 0.5348837375640869, 0.736...","[0.8178215026855469, 0.09745762497186661, 0.58...","[0.7470778226852417, 0.16487453877925873, 0.65...",1.138804,0.660006,0.465256,0.445102,0.447149,"[0.6487019062042236, 0.06666667014360428, 0.68...","[0.7716807126998901, 0.022727273404598236, 0.5...","[0.7048674821853638, 0.033898305147886276, 0.6..."

In [8]:
checkpoint = torch.load(saved_checkpoint_path, map_location=DEVICE)
checkpoint_model_config = checkpoint["model_config"]
checkpoint_builder_config = {
    key: value
    for key, value in checkpoint_model_config.items()
    if key not in {"feature_columns", "file_glob", "timeframe_file_pattern", "matched_files", "retrain_stocks", "timeframe", "base_checkpoint"}
}
inference_model = build_transformer(**checkpoint_builder_config).to(DEVICE)
inference_model.load_state_dict(checkpoint["model_state_dict"])
inference_model.eval()

x, y = val_dataset[0]
with torch.no_grad():
    output = inference_model(x.unsqueeze(0).to(DEVICE))

if checkpoint_model_config["output_type"] == "classification":
    probabilities = torch.softmax(output, dim=-1).squeeze(0).cpu()
    predicted_index = int(probabilities.argmax().item())
    labels = checkpoint["label_columns"]
    inference_result = {
        "checkpoint": saved_checkpoint_path.name,
        "base_checkpoint": checkpoint["base_checkpoint"],
        "retrain_stocks": checkpoint["retrain_stocks"],
        "timeframe": checkpoint["timeframe"],
        "predicted_label": labels[predicted_index],
        "probabilities": dict(zip(labels, probabilities.tolist())),
        "actual_index": int(y.item()),
        "actual_label": labels[int(y.item())],
    }
else:
    prediction = output.squeeze(0).cpu().tolist()
    actual = y.cpu().tolist()
    inference_result = {
        "checkpoint": saved_checkpoint_path.name,
        "base_checkpoint": checkpoint["base_checkpoint"],
        "retrain_stocks": checkpoint["retrain_stocks"],
        "timeframe": checkpoint["timeframe"],
        "prediction": dict(zip(checkpoint["target_columns"], prediction)),
        "actual": dict(zip(checkpoint["target_columns"], actual)),
    }

inference_result

{'checkpoint': 'triple_barrier_transformer_classification_AXISBANK_15minute_20260516_022110_valacc_0.6600.pt',
 'base_checkpoint': 'triple_barrier_transformer.pt',
 'retrain_stocks': ['AXISBANK'],
 'timeframe': '15minute',
 'predicted_label': 'triple_barrier_label_lower',
 'probabilities': {'triple_barrier_label_lower': 0.6293863654136658,
  'triple_barrier_label_neutral': 0.003395744366571307,
  'triple_barrier_label_upper': 0.3672179579734802},
 'actual_index': 2,
 'actual_label': 'triple_barrier_label_upper'}